import { City } from './base-game.enum';

export const Cities: { [key: string]: City } = {
  Adelaide: { name: 'Adelaide', numberIds: [21, 21, 23, 23] },
  Bendigo: { name: 'Bendigo', numberIds: [0, 0, 13, 13] },
  Brisbane: { name: 'Brisbane', numberIds: [4, 4, 4, 4] },
  BrokenHill: { name: 'Broken Hill', numberIds: [7, 7, 7, 7] },
  Geelong: { name: 'Geelong', numberIds: [20, 20, 22, 22] },
  GoldCoast: { name: 'Gold Coast', numberIds: [3, 3, 3, 3] },
  Hobart: { name: 'Hobart', numberIds: [18, 18, 19, 19] },
  Latrobe: { name: 'Latrobe', numberIds: [12, 12, 20, 20] },
  Launceston: { name: 'Launceston', numberIds: [17, 17, 18, 18] },
  LucasHeights: { name: 'Lucas Heights', numberIds: [15, 15, 16, 16] },
  Melbourne: { name: 'Melbourne', numberIds: [19, 19, 21, 21] },
  Mildura: { name: 'Mildura', numberIds: [11, 11, 12, 12] },
  MountThorley: { name: 'Mount Thorley', numberIds: [6, 6, 6, 6] },
  Newcastle: { name: 'Newcastle', numberIds: [2, 2, 2, 2] },
  OlympicDam: { name: 'Olympic Dam', numberIds: [9, 9, 10, 10] },
  PortPirie: { name: 'Port Pirie', numberIds: [10, 10, 11, 11] },
  RadiumHill: { name: 'Radium Hill', numberIds: [8, 8, 8, 8] },
  Sydney: { name: 'Sydney', numberIds: [1, 1, 1, 1] },
  Toongi: { name: 'Toongi', numberIds: [14, 14, 15, 15] },
  ToongiCoal: { name: 'Toongi (Coal Mine)', numberIds: [14, 14, 15, 15] },
  Toowoomba: { name: 'Toowoomba', numberIds: [5, 5, 5, 5] },
  WaggaWagga: { name: 'Wagga Wagga', numberIds: [13, 13, 14, 14] },
  Wollongong: { name: 'Wollongong', numberIds: [16, 16, 17, 17] },
  Wooltana: { name: 'Wooltana', numberIds: [0, 0, 9, 9] },
};
